<!-- Edited on Aug 13, 2026 @ 07:33:00 -> Suppress warnings CS0436, CA1416, and CA1422 globally for cross-platform API compatibility -->
<Project>
  <PropertyGroup>
    <Company>PAROLE Software</Company>
    <Copyright>© $([System.DateTime]::UtcNow.ToString('yyyy')) PAROLE Software - All rights reserved.</Copyright>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <NoWarn>$(NoWarn);0436;CA1416;CA1422</NoWarn>
  </PropertyGroup>
</Project>
