<!-- Edited on Aug 13, 2026 @ 07:33:00 -> Suppress warnings CS0436, CA1416, and CA1422 globally for cross-platform API compatibility -->
<Project>
  <PropertyGroup>
    <Company>PAROLE Software</Company>
    <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
    <Copyright>© $([System.DateTime]::UtcNow.ToString('yyyy')) PAROLE Software</Copyright>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <NoWarn>$(NoWarn);0436;CA1416;CA1422</NoWarn>
  </PropertyGroup>
  <ItemGroup Condition="'$(OutputType)' == 'WinExe' And '$(MSBuildProjectName)' != 'LyracistKeyGen'">
    <None Include="$(MSBuildThisFileDirectory)LICENSE" Link="LICENSE" CopyToOutputDirectory="PreserveNewest" />
    <None Include="$(MSBuildThisFileDirectory)THIRD-PARTY-NOTICES.txt" Link="THIRD-PARTY-NOTICES.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="$(MSBuildThisFileDirectory)Licenses\*.txt" Link="Licenses\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
