// <auto-generated />
// Created on Jul 28, 2026 @ 19:29:40 -> EF Migration designer class
using System;
using Lyracist.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lyracist.Data.Migrations
{
    [DbContext(typeof(LyracistDbContext))]
    [Migration("20260728232940_AddGenreToSong")]
    partial class AddGenreToSong
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Lyracist.Data.Models.EndRotationPlaylistItem", b =>
                {
                    b.Property<int>("EndRotationPlaylistItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SongId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EndRotationPlaylistItemId");

                    b.HasIndex("SongId");

                    b.ToTable("EndRotationPlaylistItems");
                });

            modelBuilder.Entity("Lyracist.Data.Models.FillInPlaylistItem", b =>
                {
                    b.Property<int>("FillInPlaylistItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SongId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FillInPlaylistItemId");

                    b.HasIndex("SongId");

                    b.ToTable("FillInPlaylistItems");
                });

            modelBuilder.Entity("Lyracist.Data.Models.MusicRequest", b =>
                {
                    b.Property<int>("MusicRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SingerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MusicRequestId");

                    b.HasIndex("SingerId");

                    b.ToTable("MusicRequests");
                });

            modelBuilder.Entity("Lyracist.Data.Models.OccasionCategory", b =>
                {
                    b.Property<int>("OccasionCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OccasionCategoryId");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("OccasionCategories");

                    b.HasData(
                        new
                        {
                            OccasionCategoryId = 1,
                            Name = "Holiday"
                        },
                        new
                        {
                            OccasionCategoryId = 2,
                            Name = "Birthday"
                        },
                        new
                        {
                            OccasionCategoryId = 3,
                            Name = "Anniversary"
                        },
                        new
                        {
                            OccasionCategoryId = 4,
                            Name = "Wedding"
                        },
                        new
                        {
                            OccasionCategoryId = 5,
                            Name = "Graduation"
                        },
                        new
                        {
                            OccasionCategoryId = 6,
                            Name = "Retirement"
                        });
                });

            modelBuilder.Entity("Lyracist.Data.Models.OccasionItem", b =>
                {
                    b.Property<int>("OccasionItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Bass")
                        .HasColumnType("REAL");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Compressor")
                        .HasColumnType("REAL");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Gain")
                        .HasColumnType("REAL");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Key")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Limiter")
                        .HasColumnType("REAL");

                    b.Property<double>("Mid")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OccasionCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Tempo")
                        .HasColumnType("REAL");

                    b.Property<double>("Treble")
                        .HasColumnType("REAL");

                    b.HasKey("OccasionItemId");

                    b.HasIndex("OccasionCategoryId");

                    b.ToTable("OccasionItems");
                });

            modelBuilder.Entity("Lyracist.Data.Models.OpeningPlaylistItem", b =>
                {
                    b.Property<int>("OpeningPlaylistItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SongId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OpeningPlaylistItemId");

                    b.HasIndex("SongId");

                    b.ToTable("OpeningPlaylistItems");
                });

            modelBuilder.Entity("Lyracist.Data.Models.RotationEntry", b =>
                {
                    b.Property<int>("RotationEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestedKey")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RequestedTempo")
                        .HasColumnType("REAL");

                    b.Property<int>("SingerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SongId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampAdded")
                        .HasColumnType("TEXT");

                    b.HasKey("RotationEntryId");

                    b.HasIndex("SingerId");

                    b.HasIndex("SongId");

                    b.ToTable("RotationEntries");
                });

            modelBuilder.Entity("Lyracist.Data.Models.Singer", b =>
                {
                    b.Property<int>("SingerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AverageRating")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSang")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RatingCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RatingPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSongsSung")
                        .HasColumnType("INTEGER");

                    b.HasKey("SingerId");

                    b.ToTable("Singers");
                });

            modelBuilder.Entity("Lyracist.Data.Models.SingerAudioSettings", b =>
                {
                    b.Property<int>("SingerAudioSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Bass")
                        .HasColumnType("REAL");

                    b.Property<double>("Compressor")
                        .HasColumnType("REAL");

                    b.Property<double>("Gain")
                        .HasColumnType("REAL");

                    b.Property<int>("Key")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Limiter")
                        .HasColumnType("REAL");

                    b.Property<double>("Mid")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SingerId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Tempo")
                        .HasColumnType("REAL");

                    b.Property<double>("Treble")
                        .HasColumnType("REAL");

                    b.HasKey("SingerAudioSettingsId");

                    b.HasIndex("SingerId")
                        .IsUnique();

                    b.ToTable("SingerAudioSettings");
                });

            modelBuilder.Entity("Lyracist.Data.Models.Song", b =>
                {
                    b.Property<int>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<double>("Duration")
                        .HasColumnType("REAL");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsKaraoke")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KaraokeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KeyDefault")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastPlayed")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TempoDefault")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SongId");

                    b.HasIndex("Artist");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.HasIndex("Title");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("Lyracist.Data.Models.SongAudioSettings", b =>
                {
                    b.Property<int>("SongAudioSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Bass")
                        .HasColumnType("REAL");

                    b.Property<double>("Compressor")
                        .HasColumnType("REAL");

                    b.Property<double>("Gain")
                        .HasColumnType("REAL");

                    b.Property<int>("Key")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Limiter")
                        .HasColumnType("REAL");

                    b.Property<double>("Mid")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SongId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Tempo")
                        .HasColumnType("REAL");

                    b.Property<double>("Treble")
                        .HasColumnType("REAL");

                    b.HasKey("SongAudioSettingsId");

                    b.HasIndex("SongId")
                        .IsUnique();

                    b.ToTable("SongAudioSettings");
                });

            modelBuilder.Entity("Lyracist.Data.Models.SongSearch", b =>
                {
                    b.Property<int>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedArtist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SongId");

                    b.ToTable("SongSearch", (string)null);

                    b.HasAnnotation("Sqlite:UseSqlReturningClause", false);
                });

            modelBuilder.Entity("Lyracist.Data.Models.EndRotationPlaylistItem", b =>
                {
                    b.HasOne("Lyracist.Data.Models.Song", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Lyracist.Data.Models.FillInPlaylistItem", b =>
                {
                    b.HasOne("Lyracist.Data.Models.Song", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Lyracist.Data.Models.MusicRequest", b =>
                {
                    b.HasOne("Lyracist.Data.Models.Singer", "Singer")
                        .WithMany("MusicRequests")
                        .HasForeignKey("SingerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Singer");
                });

            modelBuilder.Entity("Lyracist.Data.Models.OccasionCategory", b =>
                {
                    b.HasOne("Lyracist.Data.Models.OccasionCategory", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Lyracist.Data.Models.OccasionItem", b =>
                {
                    b.HasOne("Lyracist.Data.Models.OccasionCategory", "OccasionCategory")
                        .WithMany("Items")
                        .HasForeignKey("OccasionCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OccasionCategory");
                });

            modelBuilder.Entity("Lyracist.Data.Models.OpeningPlaylistItem", b =>
                {
                    b.HasOne("Lyracist.Data.Models.Song", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Lyracist.Data.Models.RotationEntry", b =>
                {
                    b.HasOne("Lyracist.Data.Models.Singer", "Singer")
                        .WithMany("RotationEntries")
                        .HasForeignKey("SingerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lyracist.Data.Models.Song", "Song")
                        .WithMany("RotationEntries")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Singer");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Lyracist.Data.Models.SingerAudioSettings", b =>
                {
                    b.HasOne("Lyracist.Data.Models.Singer", "Singer")
                        .WithOne("AudioSettings")
                        .HasForeignKey("Lyracist.Data.Models.SingerAudioSettings", "SingerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Singer");
                });

            modelBuilder.Entity("Lyracist.Data.Models.SongAudioSettings", b =>
                {
                    b.HasOne("Lyracist.Data.Models.Song", "Song")
                        .WithOne("AudioSettings")
                        .HasForeignKey("Lyracist.Data.Models.SongAudioSettings", "SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Lyracist.Data.Models.OccasionCategory", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Lyracist.Data.Models.Singer", b =>
                {
                    b.Navigation("AudioSettings");

                    b.Navigation("MusicRequests");

                    b.Navigation("RotationEntries");
                });

            modelBuilder.Entity("Lyracist.Data.Models.Song", b =>
                {
                    b.Navigation("AudioSettings");

                    b.Navigation("RotationEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
