<!-- Edited on Aug 21, 2026 @ 08:26:00 -> Include TextBoxSelectionHelper compile link -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>..\Lyracist\Assets\lyracist_mic.ico</ApplicationIcon>
    <BaseOutputPath>C:\VB26\Release\LyracistKeyGen</BaseOutputPath>
    <Title>Lyracist Key Generator</Title>
    <Authors>Dennis N. Maidon</Authors>
    <Company>PAROLE Software</Company>
    <Copyright>Copyright © 2026 PAROLE Software</Copyright>
    <PackageIcon>Lyracist_Pro.png</PackageIcon>
    <NeutralLanguage>en-US</NeutralLanguage>
    <AssemblyVersion>26.10.1.63</AssemblyVersion>
    <FileVersion>26.10.1.63</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\Lyracist\Assets\lyracist_mic.ico" Link="lyracist_mic.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="..\Lyracist\Assets\Lyracist_Pro.png" Link="Lyracist_Pro.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="4.3.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.11" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.5" />

  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Shared\EncryptionHelper.cs" Link="EncryptionHelper.cs" />
    <Compile Include="..\Shared\TextBoxSelectionHelper.cs" Link="TextBoxSelectionHelper.cs" />
    <Compile Include="..\Shared\Globals.cs" Link="Globals.cs" />
  </ItemGroup>

</Project>
