<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Sonya-Swarm-Microphone.ico</ApplicationIcon>
    <BaseOutputPath>C:\VB26\Release\LyracistKeyGen</BaseOutputPath>
    <Title>Lyracist Key Generator</Title>
    <Authors>Dennis Maidon</Authors>
    <Company>PAROLE Software</Company>
    <PackageIcon>Firefly_change name at top of logo from -Lyracist- to -Lyracist Pro- 753182.png</PackageIcon>
    <NeutralLanguage>en-US</NeutralLanguage>
    <AssemblyVersion>26.7.17.13</AssemblyVersion>
    <FileVersion>26.7.17.13</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Sonya-Swarm-Microphone.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\Users\dmaid\Downloads\Firefly_change name at top of logo from -Lyracist- to -Lyracist Pro- 753182.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="4.3.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.9" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.53.3" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Shared\EncryptionHelper.cs" Link="EncryptionHelper.cs" />
  </ItemGroup>

</Project>
